# https://www.kaggle.com/c/random-acts-of-pizza/data
random-acts-of-pizza:
  type: json
  source:
    train:  input/random-acts-of-pizza/train.json
    test:   input/random-acts-of-pizza/test.json
    output: output/random-acts-of-pizza.csv
  fields:
    request_id: id
    giver_username_if_known: categorical
    number_of_downvotes_of_request_at_retrieval: numeric
    number_of_upvotes_of_request_at_retrieval: numeric
    post_was_edited: binary
    request_number_of_comments_at_retrieval: numeric
    request_text: text
    request_text_edit_aware: text
    request_title: text
    requester_account_age_in_days_at_request: numeric,
    requester_account_age_in_days_at_retrieval: numeric
    requester_days_since_first_post_on_raop_at_request: numeric
    requester_days_since_first_post_on_raop_at_retrieval: numeric
    requester_number_of_comments_at_request: numeric
    requester_number_of_comments_at_retrieval: numeric
    requester_number_of_comments_in_raop_at_request: numeric
    requester_number_of_comments_in_raop_at_retrieval: numeric
    requester_number_of_posts_at_request: numeric
    requester_number_of_posts_at_retrieval: numeric
    requester_number_of_posts_on_raop_at_request: numeric
    requester_number_of_posts_on_raop_at_retrieval: numeric
    requester_number_of_subreddits_at_request: numeric
    requester_subreddits_at_request: list_categorical,
    requester_upvotes_minus_downvotes_at_request: numeric
    requester_upvotes_minus_downvotes_at_retrieval: numeric
    requester_upvotes_plus_downvotes_at_request: numeric
    requester_upvotes_plus_downvotes_at_retrieval: numeric
    requester_user_flair: categorical,
    requester_username: categorical,
    unix_timestamp_of_request:     date
    unix_timestamp_of_request_utc: date
  labels:
    requester_received_pizza: binary
